---
to: <%= rootDirectory %>/README.md
force: true
---
# <%= projectName %>

This project is generated by TemPlat.
https://templat.dev/

## Environment

* Node
  ver v18

## Docs
https://templat.dev/templat/usage/

## How to Install
```bash
yarn install
```
## How to Run

### Run locally
server prod
```bash
yarn dev:prod
```
server stg
```bash
yarn dev:stg
```
server local
```bash
yarn dev:dev
```

## How to Run on Server
By pushing to git, Cloud Build will deploy it to the GAE server.

for prod
```bash
git push origin master
```

for stg
```bash
git push origin stg
```
